# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plotter.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(668, 508)
        MainWindow.setMinimumSize(QtCore.QSize(200, 200))
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 320, 671, 191))
        self.stackedWidget.setObjectName("stackedWidget")
        self.main_pg_btn = QtWidgets.QWidget()
        self.main_pg_btn.setObjectName("main_pg_btn")
        self.Choose_img_btn = QtWidgets.QPushButton(self.main_pg_btn)
        self.Choose_img_btn.setGeometry(QtCore.QRect(264, 20, 143, 32))
        self.Choose_img_btn.setObjectName("Choose_img_btn")
        self.Take_pic_btn = QtWidgets.QPushButton(self.main_pg_btn)
        self.Take_pic_btn.setGeometry(QtCore.QRect(264, 70, 143, 32))
        self.Take_pic_btn.setObjectName("Take_pic_btn")
        self.horizontalSlider = QtWidgets.QSlider(self.main_pg_btn)
        self.horizontalSlider.setGeometry(QtCore.QRect(30, 50, 160, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_thresh = QtWidgets.QLabel(self.main_pg_btn)
        self.label_thresh.setGeometry(QtCore.QRect(200, 50, 40, 16))
        self.label_thresh.setObjectName("label_thresh")
        self.label_6 = QtWidgets.QLabel(self.main_pg_btn)
        self.label_6.setGeometry(QtCore.QRect(30, 20, 140, 16))
        self.label_6.setObjectName("label_6")
        self.stackedWidget.addWidget(self.main_pg_btn)
        self.process_btn_pg = QtWidgets.QWidget()
        self.process_btn_pg.setObjectName("process_btn_pg")
        self.Draw_btn = QtWidgets.QPushButton(self.process_btn_pg)
        self.Draw_btn.setGeometry(QtCore.QRect(264, 20, 143, 32))
        self.Draw_btn.setObjectName("Draw_btn")
        self.Cancel_btn = QtWidgets.QPushButton(self.process_btn_pg)
        self.Cancel_btn.setGeometry(QtCore.QRect(264, 70, 143, 32))
        self.Cancel_btn.setObjectName("Cancel_btn")
        self.stackedWidget.addWidget(self.process_btn_pg)
        self.takpic_btn_pg = QtWidgets.QWidget()
        self.takpic_btn_pg.setObjectName("takpic_btn_pg")
        self.capture_btn = QtWidgets.QPushButton(self.takpic_btn_pg)
        self.capture_btn.setGeometry(QtCore.QRect(264, 10, 143, 32))
        self.capture_btn.setObjectName("capture_btn")
        self.stackedWidget.addWidget(self.takpic_btn_pg)
        self.stackedWidget1 = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget1.setGeometry(QtCore.QRect(-1, 0, 671, 311))
        self.stackedWidget1.setObjectName("stackedWidget1")
        self.main_pg = QtWidgets.QWidget()
        self.main_pg.setObjectName("main_pg")
        self.label = QtWidgets.QLabel(self.main_pg)
        self.label.setGeometry(QtCore.QRect(81, 10, 170, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.main_pg)
        self.label_2.setGeometry(QtCore.QRect(411, 10, 170, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.main_pg)
        self.label_3.setGeometry(QtCore.QRect(30, 60, 291, 221))
        self.label_3.setText("")
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.main_pg)
        self.label_4.setGeometry(QtCore.QRect(350, 60, 291, 221))
        self.label_4.setText("")
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.stackedWidget1.addWidget(self.main_pg)
        self.cam_pg = QtWidgets.QWidget()
        self.cam_pg.setObjectName("cam_pg")
        self.viewfinder = QCameraViewfinder(self.cam_pg)
        self.viewfinder.setGeometry(QtCore.QRect(30, 30, 611, 401))
        self.viewfinder.setObjectName("viewfinder")
        self.label_5 = QtWidgets.QLabel(self.cam_pg)
        self.label_5.setGeometry(QtCore.QRect(235, 120, 200, 200))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.stackedWidget1.addWidget(self.cam_pg)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.stackedWidget1.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Choose_img_btn.setText(_translate("MainWindow", "Choose image"))
        self.Take_pic_btn.setText(_translate("MainWindow", "Take a picture"))
        self.Draw_btn.setText(_translate("MainWindow", "Draw"))
        self.Cancel_btn.setText(_translate("MainWindow", "Cancel"))
        self.label_thresh.setText(_translate("MainWindow", "0.0"))
        self.label_6.setText(_translate("MainWindow", "Adjust the threshold:"))
        self.capture_btn.setText(_translate("MainWindow", "Capture"))
        self.label.setText(_translate("MainWindow", "Original Image:"))
        self.label_2.setText(_translate("MainWindow", "Drawing Preview"))

from PyQt5.QtMultimediaWidgets import QCameraViewfinder

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

